#!/usr/bin/env python3
"""
Reads config.yaml's `deployment.nodes` list and generates:

  generated/podman-compose.<node-name>.yml   — one per node, containing only
                                                the services for that node's role(s)
  generated/nginx-lb.conf                    — upstream blocks weighted by
                                                each node's declared RAM, for
                                                every role that has >1 node
  generated/podman-compose.lb.yml            — the nginx LB container itself
                                                (only generated if needed)

Rerun this any time you add/remove/resize a node in config.yaml, then
redeploy the changed compose files on the affected hosts. Nothing about the
application code changes — services just point at the LB instead of a
single host, which config.yaml already anticipates (see the `llm.host`
comment).

Usage:
    python3 scripts/generate_compose.py
    python3 scripts/generate_compose.py --config /path/to/config.yaml
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "generated"

ROLE_SERVICES = {
    "llm": ["ollama"],
    "data": ["qdrant", "searxng", "store_postgres"],
    "orchestration": ["agent", "webui"],
}

BASE_SERVICE_DEFS = {
    "ollama": """\
  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    networks: [openlocalai_net]
    volumes:
      - openlocalai_models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
""",
    "qdrant": """\
  qdrant:
    image: docker.io/qdrant/qdrant:latest
    container_name: qdrant
    networks: [openlocalai_net]
    volumes:
      - openlocalai_qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    restart: unless-stopped
""",
    "searxng": """\
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    networks: [openlocalai_net]
    volumes:
      - openlocalai_searxng_data:/etc/searxng
    ports:
      - "8081:8080"
    restart: unless-stopped
""",
    "store_postgres": """\
  store-postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: store_postgres
    networks: [openlocalai_net]
    env_file: {repo_root}/.env
    environment:
      - POSTGRES_USER=${{STORE_PG_USER}}
      - POSTGRES_PASSWORD=${{STORE_PG_PASSWORD}}
      - POSTGRES_DB=openlocalai
    volumes:
      - openlocalai_store_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
""",
    "agent": """\
  agent:
    build:
      context: {repo_root}
      dockerfile: containers/Containerfile.agent
    container_name: openlocalai_agent
    networks: [openlocalai_net]
    env_file: {repo_root}/.env
    volumes:
      - {repo_root}/config.yaml:/app/config.yaml:ro
      - openlocalai_agent_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped
""",
    "webui": """\
  webui:
    image: docker.io/ghcr.io/open-webui/open-webui:main
    container_name: openlocalai_webui
    networks: [openlocalai_net]
    environment:
      - OLLAMA_BASE_URL={ollama_lb_url}
    volumes:
      - openlocalai_webui_data:/app/backend/data
    ports:
      - "8080:8080"
    restart: unless-stopped
""",
}

VOLUME_BY_SERVICE = {
    "ollama": ["openlocalai_models"],
    "qdrant": ["openlocalai_qdrant_data"],
    "searxng": ["openlocalai_searxng_data"],
    "store_postgres": ["openlocalai_store_pg_data"],
    "agent": ["openlocalai_agent_data"],
    "webui": ["openlocalai_webui_data"],
}


def load_deployment(config_path: Path) -> dict:
    with open(config_path) as f:
        cfg = yaml.safe_load(f)
    return cfg.get("deployment", {})


def nodes_by_role(nodes: list[dict]) -> dict[str, list[dict]]:
    result: dict[str, list[dict]] = {}
    for node in nodes:
        for role in node.get("roles", []):
            result.setdefault(role, []).append(node)
    return result


def render_node_compose(node: dict, ollama_lb_url: str) -> str:
    services_yaml = []
    volumes = set()
    for role in node["roles"]:
        for svc in ROLE_SERVICES.get(role, []):
            tmpl = BASE_SERVICE_DEFS[svc]
            services_yaml.append(
                tmpl.format(repo_root=str(REPO_ROOT), ollama_lb_url=ollama_lb_url)
            )
            volumes.update(VOLUME_BY_SERVICE[svc])

    volumes_block = "\n".join(f"  {v}:" for v in sorted(volumes)) or "  {}"

    return f"""\
# Auto-generated by scripts/generate_compose.py — do not hand-edit.
# Node: {node['name']}  (host: {node['host']}, roles: {node['roles']})
# Deploy on this host with: podman-compose -f podman-compose.{node['name']}.yml up -d

version: "3.8"

networks:
  openlocalai_net:
    driver: bridge

volumes:
{volumes_block}

services:
{''.join(services_yaml)}
"""


def compute_weights(role_nodes: list[dict]) -> list[tuple[dict, int]]:
    """Weight = proportional share of total RAM declared for this role.
    nginx weights must be integers >=1, so scale to a 1-100 range."""
    total_ram = sum(n["resources"]["ram_gb"] for n in role_nodes)
    weighted = []
    for n in role_nodes:
        share = n["resources"]["ram_gb"] / total_ram
        weight = max(1, round(share * 100))
        weighted.append((n, weight))
    return weighted


def render_nginx_conf(nodes: list[dict], deployment: dict) -> str | None:
    by_role = nodes_by_role(nodes)
    lb_cfg = deployment.get("load_balancing", {})

    upstream_blocks = []
    server_blocks = []

    if len(by_role.get("llm", [])) > 1:
        weighted = compute_weights(by_role["llm"])
        lines = "\n".join(
            f"    server {n['host']}:11434 weight={w};" for n, w in weighted
        )
        upstream_blocks.append(f"upstream llm_backend {{\n{lines}\n}}")
        server_blocks.append(f"""
server {{
    listen {lb_cfg.get('llm_lb_port', 11434)};
    location / {{
        proxy_pass http://llm_backend;
        proxy_read_timeout 300s;
    }}
}}""")

    if len(by_role.get("orchestration", [])) > 1:
        weighted = compute_weights(by_role["orchestration"])
        lines = "\n".join(
            f"    server {n['host']}:8000 weight={w};" for n, w in weighted
        )
        upstream_blocks.append(f"upstream orchestration_backend {{\n{lines}\n}}")
        server_blocks.append(f"""
server {{
    listen {lb_cfg.get('orchestration_lb_port', 8000)};
    location / {{
        proxy_pass http://orchestration_backend;
        proxy_read_timeout 300s;
    }}
}}""")

    if not upstream_blocks:
        return None  # no role has more than one node — no LB needed

    return (
        "# Auto-generated by scripts/generate_compose.py — do not hand-edit.\n"
        "# Weights are proportional to each node's declared RAM in config.yaml.\n"
        "events {}\n\nhttp {\n"
        + "\n\n".join(upstream_blocks)
        + "\n"
        + "\n".join(server_blocks)
        + "\n}\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default=str(REPO_ROOT / "config.yaml"))
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"ERROR: {config_path} not found. Copy config.yaml.example to config.yaml first.")
        sys.exit(1)

    deployment = load_deployment(config_path)
    nodes = deployment.get("nodes", [])
    if not nodes:
        print("ERROR: config.yaml has no deployment.nodes defined.")
        sys.exit(1)

    OUT_DIR.mkdir(exist_ok=True)

    by_role = nodes_by_role(nodes)
    llm_nodes = by_role.get("llm", [])
    if len(llm_nodes) > 1:
        ollama_lb_url = f"http://{deployment['load_balancing'].get('lb_node_host', llm_nodes[0]['host'])}:11434"
    elif llm_nodes:
        ollama_lb_url = f"http://{llm_nodes[0]['host']}:11434"
    else:
        ollama_lb_url = "http://ollama:11434"

    for node in nodes:
        out_path = OUT_DIR / f"podman-compose.{node['name']}.yml"
        out_path.write_text(render_node_compose(node, ollama_lb_url))
        print(f"wrote {out_path}")

    nginx_conf = render_nginx_conf(nodes, deployment)
    if nginx_conf:
        nginx_path = OUT_DIR / "nginx-lb.conf"
        nginx_path.write_text(nginx_conf)
        print(f"wrote {nginx_path}  (load balancing is active — multiple nodes share a role)")

        lb_compose = f"""\
# Auto-generated by scripts/generate_compose.py — do not hand-edit.
# Deploy on the LB node with: podman-compose -f podman-compose.lb.yml up -d
version: "3.8"
services:
  nginx-lb:
    image: docker.io/library/nginx:alpine
    container_name: openlocalai_lb
    volumes:
      - {OUT_DIR}/nginx-lb.conf:/etc/nginx/nginx.conf:ro
    network_mode: host
    restart: unless-stopped
"""
        (OUT_DIR / "podman-compose.lb.yml").write_text(lb_compose)
        print(f"wrote {OUT_DIR / 'podman-compose.lb.yml'}")
    else:
        print("no role has more than one node — no load balancer needed yet")

    print("\nDone. Copy each generated/podman-compose.<node>.yml to its "
          "matching host and run `podman-compose -f <file> up -d` there.")


if __name__ == "__main__":
    main()
